services:
  app:
    image: rest
    container_name: rest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      app-network:
        ipv4_address: 172.27.0.3
    ports:
      - "8060:8080"
    volumes:
      - /home/angel/proyectos_spring/REST/upload:/root/upload
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "141198"
      MYSQL_DATABASE: "rest-api-db"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "141198"
    ports:
      - "3318:3306"
    networks:
      app-network:
        ipv4_address: 172.27.0.4
  #  healthcheck:
  #      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent"]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 5

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
