services:
  mysql-service-5:
    image: 'mysql:latest'

    environment:
      MYSQL_ROOT_PASSWORD: '141198'
      MYSQL_DATABASE: 'rest-api-db'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: '141198'
    ports:
      - '3318:3306'
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent"]
        interval: 30s
        timeout: 10s
        retries: 5

networks:
  app-network:
    driver: bridge